### ISSUE TITLE
testing on windows plateform

### ISSUE THREAD

**Issue by akhlaaqbadulla** [jasonknight/salor-retail#21]
hello i have been able to use it on my debian distro but i have been trying to install on my windows pc and i have been strugling to do so. am a newbie to ruby and i am still trying to find my around. Can you please tell me what i can do to make it work on windows.

**Comment by jasonknight** [comment]
Yeah, we gave up trying to get rails to play well on windows. It was just a pain. It's probably possible for you to get salor-bin running on windows and just connect to a server box.

**Comment by akhlaaqbadulla** [comment]
thanks but i got it to work on windows. actually the was an issues with my ruby configuration. now i fixed it.. it works now i need to know how and will it break?.

**Comment by akhlaaqbadulla** [comment]
a short lived happiness i got this error...
`Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-1.7.3/ext/json/ext/generator
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20180302-220-16jb76i.rb extconf.rb
creating Makefile

current directory:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-1.7.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-1.7.3/ext/json/ext/generator
make "DESTDIR="
generating generator-x64-mingw32.def
compiling generator.c
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function 'fbuffer_to_s':
../fbuffer/fbuffer.h:158:47: error: macro "rb_str_new" requires 2 arguments, but
only 1 given
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                               ^
../fbuffer/fbuffer.h:158:20: warning: initialization makes integer from pointer
without a cast [-Wint-conversion]
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                    ^~~~~~~~~~
In file included from generator.c:2:0:
generator.c: In function 'cState_aref':
generator.h:96:27: warning: variable 'state' set but not used
[-Wunused-but-set-variable]
     JSON_Generator_State *state;              \
                           ^
generator.h:96:27: note: in definition of macro 'GET_STATE'
     JSON_Generator_State *state;              \
                           ^~~~~
generator.c: In function 'generate_json':
generator.c:800:25: error: 'rb_cFixnum' undeclared (first use in this function);
did you mean 'mFixnum'?
     } else if (klass == rb_cFixnum) {
                         ^~~~~~~~~~
                         mFixnum
generator.c:800:25: note: each undeclared identifier is reported only once for
each function it appears in
generator.c:802:25: error: 'rb_cBignum' undeclared (first use in this function);
did you mean 'rb_cFixnum'?
     } else if (klass == rb_cBignum) {
                         ^~~~~~~~~~
                         rb_cFixnum
generator.c: In function 'isArrayOrObject':
generator.c:867:22: warning: suggest parentheses around '&&' within '||'
[-Wparentheses]
     return *p == '[' && *q == ']' || *p == '{' && *q == '}';
            ~~~~~~~~~~^~~~~~~~~~~~
make: *** [Makefile:242: generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-1.7.3 for inspection.
Results logged to
C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/json-1.7.3/gem_make.out

An error occurred while installing json (1.7.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.7.3'` succeeds before bundling.

In Gemfile:
  coffee-rails was resolved to 3.2.2, which depends on
    railties was resolved to 3.2.6, which depends on
      rdoc was resolved to 3.12.2, which depends on
        json`

**Comment by jasonknight** [comment]
Yeah, welcome to Ruby :)

I've considered porting the application to a better language, like PHP which is much easier to deploy. I didn't realize anyone actually used the software...

**Comment by akhlaaqbadulla** [comment]
actually its a really nice software i used it on my debian system. well if you need help porting to php i can help as i will start learning php.

**Comment by jasonknight** [comment]
Thank you. Most of the credit goes to my partner in crime, mifranzl, he did the rewrite and retest of the latest salor (well, old now but latest way back). And he designed the deb packaging and distribution etc. Good luck!
